---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo=TRUE}
act<-read.csv(unz("activity.zip","activity.csv"), header=TRUE, sep=",")
act$date<-as.Date(as.character(act$date),"%Y-%m-%d")
```


## What is mean total number of steps taken per day?
```{r, echo=TRUE}
library(dplyr,warn.conflicts = FALSE)
by_date<-group_by(act,date)
dailysteps<-summarise(by_date,tsteps=sum(steps))
mean(dailysteps$tsteps,na.rm=TRUE)
median(dailysteps$tsteps,na.rm=TRUE)
```


## What is the average daily activity pattern?
```{r, echo=TRUE}
by_interval<-group_by(act,interval)
dayact<-summarise(by_interval, intsteps=mean(steps,na.rm=TRUE))
plot(dayact,type="l",ylab="Average steps",main="Daily activity")
dayact[which.max(dayact$intsteps),]
```
## Imputing missing values
```{r, echo=TRUE}
sum(is.na(act$steps))
## mean for the 5 minute interval is used to fill NAs
actn<-act
actn$steps[is.na(act$steps)]<-dayact$intsteps[match(act$interval[is.na(act$steps)], dayact$interval)]
by_daten<-group_by(actn,date)
dailystepsn<-summarise(by_daten,tsteps=sum(steps))
mean(dailystepsn$tsteps)
median(dailystepsn$tsteps)
```
### Mean has remained same, while Median has become equal to mean due to imputing missing values

## Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
library(ggplot2)
actn$daytype<-ifelse(weekdays(actn$date,abbreviate=TRUE) %in% c("Sat","Sun"), "weekend","weekday")
actn$daytype<-as.factor(actn$daytype)
by_intervaln<-group_by(actn,interval,daytype)
dayactn<-summarise(by_intervaln, intsteps=mean(steps,na.rm=TRUE))
ggplot(dayactn,aes(interval,intsteps,group=daytype))+geom_line()+facet_wrap(~daytype,ncol=1)+labs(y="Number of steps",title="Daily activity ")
```